fix: cache config enum (#628)
This will be followed by a sequence of work on improving the l1
cache/shared memory configuration implementation as stated
[here](https://github.com/NVIDIA/numba-cuda/issues/617#issuecomment-3599322414).

This PR fixes the following bug:
```
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/discourse-3080/repro.py", line 13, in <module>
    cufunc.cache_config(prefer_shared=True)
  File "/home/gmarkall/numbadev/numba-cuda/numba_cuda/numba/cuda/cudadrv/driver.py", line 2418, in cache_config
    flag = attr.CU_FUNC_CACHE_PREFER_SHARED
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'CUfunction_attribute' has no attribute 'CU_FUNC_CACHE_PREFER_SHARED'
``` 

with a test that would ensure that this won't regress.