Fix max block size computation in `forall` (#744)
PR https://github.com/NVIDIA/numba-cuda/pull/609 made some changes to
the way modules were loaded that results in the wrong object being
passed to `cuOccupancyMaxPotentialBlockSize` (previously a `CUFunction`
and now a `CUKernel`). This causes the max block size calculation to
fail after eventually getting the wrong object and leads to a
`CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES` on certain GPUs. This is observable
on a V100 with a resource hungry kernel:

```
python -m numba.runtests numba.cuda.tests.cudapy.test_gufunc.TestCUDAGufunc.test_gufunc_small
```
```
cuda.core._utils.cuda_utils.CUDAError: CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES: This indicates that a launch did not occur because it did not have appropriate resources. 
```

This PR removes the `numba-cuda` native maximum threads per block
computation machinery and routes through `cuda-python` APIs to get the
same information.